### ISSUE TITLE
[Bug]当配置文件所处的文件夹不存在时，应用崩溃

### ISSUE THREAD

**Issue by Baka632** [QingXia-Ela/MonsterSirenDesktop#1]
应用启动时似乎不会检查配置文件所在的文件夹是否存在，因此当应用第一次启动时，应用崩溃，提示如下：
![image](https://github.com/QingXia-Ela/MonsterSirenDesktop/assets/48171809/5576a23f-0ccb-4a62-b79b-540b1832805b)

**Comment by QingXia-Ela** [comment]
Fix at: https://github.com/QingXia-Ela/MonsterSirenDesktop/commit/07f61060b77632dba768ab493623d0714e1b05fe
