### ISSUE TITLE
能否提供可执行文件

### ISSUE THREAD

**Issue by Baka632** [QingXia-Ela/MonsterSirenDesktop#3]
我这里用源代码生成有点困难（大概是因为环境没有配置好）
希望能够获取能够直接运行的可执行文件qwq

**Comment by QingXia-Ela** [comment]
> 我这里用源代码生成有点困难（大概是因为环境没有配置好） 希望能够获取能够直接运行的可执行文件qwq

是构建的时候出错吗还是怎么说，有没有截图报错可以看一眼，这两天会发一个可执行的 exe 进行测试。

**Comment by Baka632** [comment]
运行 `pnpm run tauri ` 命令后就一直卡在这里了

![image](https://github.com/user-attachments/assets/e25bc9f8-24ad-4d99-acaa-22ae2ef9dd8c)

如果进入 `http://localhost:8000/` ，则出现以下内容：

![image](https://github.com/user-attachments/assets/de0fed7b-330e-40ff-b1b8-17c9baefa5cb)

**Comment by QingXia-Ela** [comment]
> 运行 `pnpm run tauri ` 命令后就一直卡在这里了

rust 构建的话可以 google 看看解决方案，或者重启电脑

pnpm 包不存在可能是依赖更新了，重新尝试 `pnpm i`

**Comment by QingXia-Ela** [comment]
打包已发：https://github.com/QingXia-Ela/MonsterSirenDesktop/releases/tag/v0.0.1-alpha
